"""Shared country-name aliases for non-ISO sources."""

from __future__ import annotations

# Heritage / common English names -> ISO alpha-3
NAME_TO_ISO: dict[str, str] = {
    "afghanistan": "AFG",
    "albania": "ALB",
    "algeria": "DZA",
    "angola": "AGO",
    "argentina": "ARG",
    "armenia": "ARM",
    "australia": "AUS",
    "austria": "AUT",
    "azerbaijan": "AZE",
    "bahamas": "BHS",
    "bahrain": "BHR",
    "bangladesh": "BGD",
    "barbados": "BRB",
    "belarus": "BLR",
    "belgium": "BEL",
    "belize": "BLZ",
    "benin": "BEN",
    "bhutan": "BTN",
    "bolivia": "BOL",
    "bosnia and herzegovina": "BIH",
    "botswana": "BWA",
    "brazil": "BRA",
    "brunei darussalam": "BRN",
    "brunei": "BRN",
    "bulgaria": "BGR",
    "burkina faso": "BFA",
    "burundi": "BDI",
    "cabo verde": "CPV",
    "cape verde": "CPV",
    "cambodia": "KHM",
    "cameroon": "CMR",
    "canada": "CAN",
    "central african republic": "CAF",
    "chad": "TCD",
    "chile": "CHL",
    "china": "CHN",
    "colombia": "COL",
    "comoros": "COM",
    "congo dem rep": "COD",
    "congo democratic republic": "COD",
    "congo democratic republic of the congo": "COD",
    "congo republic": "COG",
    "democratic republic of the congo": "COD",
    "democratic republic of congo": "COD",
    "congo republic of": "COG",
    "republic of the congo": "COG",
    "congo": "COG",
    "sao tome and principe": "STP",
    "são tomé and príncipe": "STP",
    "costa rica": "CRI",
    "croatia": "HRV",
    "cuba": "CUB",
    "cyprus": "CYP",
    "czech republic": "CZE",
    "czechia": "CZE",
    "denmark": "DNK",
    "djibouti": "DJI",
    "dominican republic": "DOM",
    "ecuador": "ECU",
    "egypt": "EGY",
    "el salvador": "SLV",
    "equatorial guinea": "GNQ",
    "eritrea": "ERI",
    "estonia": "EST",
    "eswatini": "SWZ",
    "swaziland": "SWZ",
    "ethiopia": "ETH",
    "fiji": "FJI",
    "finland": "FIN",
    "france": "FRA",
    "gabon": "GAB",
    "gambia": "GMB",
    "the gambia": "GMB",
    "georgia": "GEO",
    "germany": "DEU",
    "ghana": "GHA",
    "greece": "GRC",
    "guatemala": "GTM",
    "guinea": "GIN",
    "guinea bissau": "GNB",
    "guyana": "GUY",
    "haiti": "HTI",
    "honduras": "HND",
    "hong kong": "HKG",
    "hong kong sar": "HKG",
    "hungary": "HUN",
    "iceland": "ISL",
    "india": "IND",
    "indonesia": "IDN",
    "iran": "IRN",
    "iraq": "IRQ",
    "ireland": "IRL",
    "israel": "ISR",
    "italy": "ITA",
    "jamaica": "JAM",
    "japan": "JPN",
    "jordan": "JOR",
    "kazakhstan": "KAZ",
    "kenya": "KEN",
    "korea south": "KOR",
    "korea north": "PRK",
    "north korea": "PRK",
    "south korea": "KOR",
    "republic of korea": "KOR",
    "korea": "KOR",
    "kuwait": "KWT",
    "kyrgyzstan": "KGZ",
    "kyrgyz republic": "KGZ",
    "laos": "LAO",
    "lao pdr": "LAO",
    "latvia": "LVA",
    "lebanon": "LBN",
    "lesotho": "LSO",
    "liberia": "LBR",
    "libya": "LBY",
    "lithuania": "LTU",
    "luxembourg": "LUX",
    "madagascar": "MDG",
    "malawi": "MWI",
    "malaysia": "MYS",
    "maldives": "MDV",
    "mali": "MLI",
    "malta": "MLT",
    "mauritania": "MRT",
    "mauritius": "MUS",
    "mexico": "MEX",
    "moldova": "MDA",
    "mongolia": "MNG",
    "montenegro": "MNE",
    "morocco": "MAR",
    "mozambique": "MOZ",
    "myanmar": "MMR",
    "burma": "MMR",
    "namibia": "NAM",
    "nepal": "NPL",
    "netherlands": "NLD",
    "new zealand": "NZL",
    "nicaragua": "NIC",
    "niger": "NER",
    "nigeria": "NGA",
    "north macedonia": "MKD",
    "macedonia": "MKD",
    "norway": "NOR",
    "oman": "OMN",
    "pakistan": "PAK",
    "panama": "PAN",
    "papua new guinea": "PNG",
    "paraguay": "PRY",
    "peru": "PER",
    "philippines": "PHL",
    "poland": "POL",
    "portugal": "PRT",
    "qatar": "QAT",
    "romania": "ROU",
    "russia": "RUS",
    "russian federation": "RUS",
    "rwanda": "RWA",
    "saudi arabia": "SAU",
    "senegal": "SEN",
    "serbia": "SRB",
    "seychelles": "SYC",
    "sierra leone": "SLE",
    "singapore": "SGP",
    "slovakia": "SVK",
    "slovak republic": "SVK",
    "slovenia": "SVN",
    "solomon islands": "SLB",
    "somalia": "SOM",
    "south africa": "ZAF",
    "south sudan": "SSD",
    "spain": "ESP",
    "sri lanka": "LKA",
    "sudan": "SDN",
    "suriname": "SUR",
    "sweden": "SWE",
    "switzerland": "CHE",
    "syria": "SYR",
    "taiwan": "TWN",
    "taiwan province of china": "TWN",
    "tajikistan": "TJK",
    "tanzania": "TZA",
    "thailand": "THA",
    "timor leste": "TLS",
    "togo": "TGO",
    "trinidad and tobago": "TTO",
    "tunisia": "TUN",
    "turkey": "TUR",
    "turkiye": "TUR",
    "türkiye": "TUR",
    "turkmenistan": "TKM",
    "uganda": "UGA",
    "ukraine": "UKR",
    "united arab emirates": "ARE",
    "uae": "ARE",
    "united kingdom": "GBR",
    "uk": "GBR",
    "united states": "USA",
    "united states of america": "USA",
    "usa": "USA",
    "uruguay": "URY",
    "uzbekistan": "UZB",
    "vanuatu": "VUT",
    "venezuela": "VEN",
    "vietnam": "VNM",
    "viet nam": "VNM",
    "yemen": "YEM",
    "zambia": "ZMB",
    "zimbabwe": "ZWE",
    "cote d ivoire": "CIV",
    "côte d ivoire": "CIV",
    "ivory coast": "CIV",
    "sao tome and principe": "STP",
    "são tomé and príncipe": "STP",
    "west bank and gaza": "PSE",
}


def resolve_iso_from_name(name: str, normalize_fn) -> str | None:
    key = normalize_fn(name)
    if key in NAME_TO_ISO:
        return NAME_TO_ISO[key]
    # try without leading "the "
    if key.startswith("the "):
        key2 = key[4:]
        if key2 in NAME_TO_ISO:
            return NAME_TO_ISO[key2]
    return None
