/**
 * Static Quick Facts: language and currency by ISO 3166-1 alpha-3.
 * Display-only — does not feed MVI scoring.
 */

export interface CountryQuickFacts {
  language: string;
  currency: string;
  currencySymbol: string;
}

export const COUNTRY_QUICK_FACTS: Record<string, CountryQuickFacts> = {
  AFG: { language: "Dari, Pashto", currency: "AFN (Af)", currencySymbol: "Af" },
  AGO: { language: "Portuguese", currency: "AOA (Kz)", currencySymbol: "Kz" },
  ALB: { language: "Albanian", currency: "ALL (L)", currencySymbol: "L" },
  AND: { language: "Catalan", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  ARE: { language: "Arabic, English", currency: "AED (AED)", currencySymbol: "AED" },
  ARG: { language: "Spanish", currency: "ARS ($)", currencySymbol: "$" },
  ARM: { language: "Armenian", currency: "AMD (AMD)", currencySymbol: "AMD" },
  ATA: { language: "English", currency: "USD ($)", currencySymbol: "$" },
  ATF: { language: "French", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  ATG: { language: "English", currency: "XCD ($)", currencySymbol: "$" },
  AUS: { language: "English", currency: "AUD (A$)", currencySymbol: "A$" },
  AUT: { language: "German", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  AZE: { language: "Azerbaijani", currency: "AZN (AZN)", currencySymbol: "AZN" },
  BDI: { language: "Kirundi, French", currency: "BIF (FBu)", currencySymbol: "FBu" },
  BEL: { language: "Dutch, French, German", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  BEN: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  BFA: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  BGD: { language: "Bengali", currency: "BDT (Tk)", currencySymbol: "Tk" },
  BGR: { language: "Bulgarian", currency: "BGN (\u043B\u0432)", currencySymbol: "\u043B\u0432" },
  BHR: { language: "Arabic, English", currency: "BHD (BD)", currencySymbol: "BD" },
  BHS: { language: "English", currency: "BSD ($)", currencySymbol: "$" },
  BIH: { language: "Bosnian, Croatian, Serbian", currency: "BAM (KM)", currencySymbol: "KM" },
  BLR: { language: "Belarusian, Russian", currency: "BYN (Br)", currencySymbol: "Br" },
  BLZ: { language: "English", currency: "BZD ($)", currencySymbol: "$" },
  BOL: { language: "Spanish", currency: "BOB (Bs)", currencySymbol: "Bs" },
  BRA: { language: "Portuguese", currency: "BRL (R$)", currencySymbol: "R$" },
  BRB: { language: "English", currency: "BBD ($)", currencySymbol: "$" },
  BRN: { language: "Malay, English", currency: "BND (B$)", currencySymbol: "B$" },
  BTN: { language: "Dzongkha", currency: "BTN (Nu)", currencySymbol: "Nu" },
  BWA: { language: "English, Setswana", currency: "BWP (P)", currencySymbol: "P" },
  CAF: { language: "French", currency: "XAF (FCFA)", currencySymbol: "FCFA" },
  CAN: { language: "English, French", currency: "CAD (C$)", currencySymbol: "C$" },
  CHE: { language: "German, French, Italian", currency: "CHF (CHF)", currencySymbol: "CHF" },
  CHL: { language: "Spanish", currency: "CLP ($)", currencySymbol: "$" },
  CHN: { language: "Mandarin", currency: "CNY (\u00A5)", currencySymbol: "\u00A5" },
  CIV: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  CMR: { language: "French, English", currency: "XAF (FCFA)", currencySymbol: "FCFA" },
  COD: { language: "French", currency: "CDF (FC)", currencySymbol: "FC" },
  COG: { language: "French", currency: "XAF (FCFA)", currencySymbol: "FCFA" },
  COL: { language: "Spanish", currency: "COP ($)", currencySymbol: "$" },
  COM: { language: "Comorian, French, Arabic", currency: "KMF (CF)", currencySymbol: "CF" },
  CPV: { language: "Portuguese", currency: "CVE ($)", currencySymbol: "$" },
  CRI: { language: "Spanish", currency: "CRC (\u20A1)", currencySymbol: "\u20A1" },
  CUB: { language: "Spanish", currency: "CUP ($)", currencySymbol: "$" },
  CYP: { language: "Greek, Turkish", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  CZE: { language: "Czech", currency: "CZK (K\u010D)", currencySymbol: "K\u010D" },
  DEU: { language: "German", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  DJI: { language: "French, Arabic", currency: "DJF (Fdj)", currencySymbol: "Fdj" },
  DMA: { language: "English", currency: "XCD ($)", currencySymbol: "$" },
  DNK: { language: "Danish", currency: "DKK (kr)", currencySymbol: "kr" },
  DOM: { language: "Spanish", currency: "DOP ($)", currencySymbol: "$" },
  DZA: { language: "Arabic, French", currency: "DZD (DA)", currencySymbol: "DA" },
  ECU: { language: "Spanish", currency: "USD ($)", currencySymbol: "$" },
  EGY: { language: "Arabic", currency: "EGP (E\u00A3)", currencySymbol: "E\u00A3" },
  ERI: { language: "Tigrinya, Arabic, English", currency: "ERN (Nfk)", currencySymbol: "Nfk" },
  ESH: { language: "Arabic, Spanish", currency: "MAD (DH)", currencySymbol: "DH" },
  ESP: { language: "Spanish", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  EST: { language: "Estonian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  ETH: { language: "Amharic", currency: "ETB (Br)", currencySymbol: "Br" },
  FIN: { language: "Finnish, Swedish", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  FJI: { language: "English, Fijian", currency: "FJD (FJ$)", currencySymbol: "FJ$" },
  FLK: { language: "English", currency: "FKP (\u00A3)", currencySymbol: "\u00A3" },
  FRA: { language: "French", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  FSM: { language: "English", currency: "USD ($)", currencySymbol: "$" },
  GAB: { language: "French", currency: "XAF (FCFA)", currencySymbol: "FCFA" },
  GBR: { language: "English", currency: "GBP (\u00A3)", currencySymbol: "\u00A3" },
  GEO: { language: "Georgian", currency: "GEL (\u20BE)", currencySymbol: "\u20BE" },
  GHA: { language: "English", currency: "GHS (GH\u20B5)", currencySymbol: "GH\u20B5" },
  GIN: { language: "French", currency: "GNF (FG)", currencySymbol: "FG" },
  GMB: { language: "English", currency: "GMD (D)", currencySymbol: "D" },
  GNB: { language: "Portuguese", currency: "XOF (CFA)", currencySymbol: "CFA" },
  GNQ: { language: "Spanish, French, Portuguese", currency: "XAF (FCFA)", currencySymbol: "FCFA" },
  GRC: { language: "Greek", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  GRD: { language: "English", currency: "XCD ($)", currencySymbol: "$" },
  GRL: { language: "Greenlandic, Danish", currency: "DKK (kr)", currencySymbol: "kr" },
  GTM: { language: "Spanish", currency: "GTQ (Q)", currencySymbol: "Q" },
  GUY: { language: "English", currency: "GYD ($)", currencySymbol: "$" },
  HND: { language: "Spanish", currency: "HNL (L)", currencySymbol: "L" },
  HRV: { language: "Croatian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  HTI: { language: "Haitian Creole, French", currency: "HTG (G)", currencySymbol: "G" },
  HUN: { language: "Hungarian", currency: "HUF (Ft)", currencySymbol: "Ft" },
  IDN: { language: "Indonesian", currency: "IDR (Rp)", currencySymbol: "Rp" },
  IND: { language: "Hindi, English", currency: "INR (\u20B9)", currencySymbol: "\u20B9" },
  IRL: { language: "English, Irish", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  IRN: { language: "Persian", currency: "IRR (IRR)", currencySymbol: "IRR" },
  IRQ: { language: "Arabic, Kurdish", currency: "IQD (IQD)", currencySymbol: "IQD" },
  ISL: { language: "Icelandic", currency: "ISK (kr)", currencySymbol: "kr" },
  ISR: { language: "Hebrew, Arabic", currency: "ILS (\u20AA)", currencySymbol: "\u20AA" },
  ITA: { language: "Italian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  JAM: { language: "English", currency: "JMD ($)", currencySymbol: "$" },
  JOR: { language: "Arabic", currency: "JOD (JD)", currencySymbol: "JD" },
  JPN: { language: "Japanese", currency: "JPY (\u00A5)", currencySymbol: "\u00A5" },
  KAZ: { language: "Kazakh, Russian", currency: "KZT (\u20B8)", currencySymbol: "\u20B8" },
  KEN: { language: "English, Swahili", currency: "KES (KSh)", currencySymbol: "KSh" },
  KGZ: { language: "Kyrgyz, Russian", currency: "KGS (\u0441)", currencySymbol: "\u0441" },
  KHM: { language: "Khmer", currency: "KHR (KHR)", currencySymbol: "KHR" },
  KIR: { language: "English, Gilbertese", currency: "AUD (A$)", currencySymbol: "A$" },
  KNA: { language: "English", currency: "XCD ($)", currencySymbol: "$" },
  KOR: { language: "Korean", currency: "KRW (\u20A9)", currencySymbol: "\u20A9" },
  KWT: { language: "Arabic, English", currency: "KWD (KD)", currencySymbol: "KD" },
  LAO: { language: "Lao", currency: "LAK (\u20AD)", currencySymbol: "\u20AD" },
  LBN: { language: "Arabic, French, English", currency: "LBP (L\u00A3)", currencySymbol: "L\u00A3" },
  LBR: { language: "English", currency: "LRD ($)", currencySymbol: "$" },
  LBY: { language: "Arabic", currency: "LYD (LD)", currencySymbol: "LD" },
  LCA: { language: "English", currency: "XCD ($)", currencySymbol: "$" },
  LIE: { language: "German", currency: "CHF (CHF)", currencySymbol: "CHF" },
  LKA: { language: "Sinhala, Tamil", currency: "LKR (Rs)", currencySymbol: "Rs" },
  LSO: { language: "English, Sesotho", currency: "LSL (L)", currencySymbol: "L" },
  LTU: { language: "Lithuanian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  LUX: { language: "Luxembourgish, French, German", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  LVA: { language: "Latvian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  MAR: { language: "Arabic, French", currency: "MAD (DH)", currencySymbol: "DH" },
  MCO: { language: "French", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  MDA: { language: "Romanian", currency: "MDL (L)", currencySymbol: "L" },
  MDG: { language: "Malagasy, French", currency: "MGA (Ar)", currencySymbol: "Ar" },
  MDV: { language: "Dhivehi", currency: "MVR (Rf)", currencySymbol: "Rf" },
  MEX: { language: "Spanish", currency: "MXN ($)", currencySymbol: "$" },
  MHL: { language: "Marshallese, English", currency: "USD ($)", currencySymbol: "$" },
  MKD: { language: "Macedonian", currency: "MKD (den)", currencySymbol: "den" },
  MLI: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  MLT: { language: "Maltese, English", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  MMR: { language: "Burmese", currency: "MMK (K)", currencySymbol: "K" },
  MNE: { language: "Montenegrin", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  MNG: { language: "Mongolian", currency: "MNT (\u20AE)", currencySymbol: "\u20AE" },
  MOZ: { language: "Portuguese", currency: "MZN (MT)", currencySymbol: "MT" },
  MRT: { language: "Arabic", currency: "MRU (UM)", currencySymbol: "UM" },
  MUS: { language: "English, French", currency: "MUR (Rs)", currencySymbol: "Rs" },
  MWI: { language: "English, Chichewa", currency: "MWK (MK)", currencySymbol: "MK" },
  MYS: { language: "Malay, English", currency: "MYR (RM)", currencySymbol: "RM" },
  NAM: { language: "English", currency: "NAD ($)", currencySymbol: "$" },
  NCL: { language: "French", currency: "XPF (CFP)", currencySymbol: "CFP" },
  NER: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  NGA: { language: "English", currency: "NGN (\u20A6)", currencySymbol: "\u20A6" },
  NIC: { language: "Spanish", currency: "NIO (C$)", currencySymbol: "C$" },
  NLD: { language: "Dutch", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  NOR: { language: "Norwegian", currency: "NOK (kr)", currencySymbol: "kr" },
  NPL: { language: "Nepali", currency: "NPR (Rs)", currencySymbol: "Rs" },
  NRU: { language: "Nauruan, English", currency: "AUD (A$)", currencySymbol: "A$" },
  NZL: { language: "English, Maori", currency: "NZD (NZ$)", currencySymbol: "NZ$" },
  OMN: { language: "Arabic", currency: "OMR (OMR)", currencySymbol: "OMR" },
  PAK: { language: "Urdu, English", currency: "PKR (Rs)", currencySymbol: "Rs" },
  PAN: { language: "Spanish", currency: "PAB (B/.)", currencySymbol: "B/." },
  PER: { language: "Spanish", currency: "PEN (S/)", currencySymbol: "S/" },
  PHL: { language: "Filipino, English", currency: "PHP (\u20B1)", currencySymbol: "\u20B1" },
  PLW: { language: "Palauan, English", currency: "USD ($)", currencySymbol: "$" },
  PNG: { language: "English, Tok Pisin", currency: "PGK (K)", currencySymbol: "K" },
  POL: { language: "Polish", currency: "PLN (z\u0142)", currencySymbol: "z\u0142" },
  PRI: { language: "Spanish, English", currency: "USD ($)", currencySymbol: "$" },
  PRK: { language: "Korean", currency: "KPW (\u20A9)", currencySymbol: "\u20A9" },
  PRT: { language: "Portuguese", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  PRY: { language: "Spanish, Guarani", currency: "PYG (\u20B2)", currencySymbol: "\u20B2" },
  PSE: { language: "Arabic", currency: "ILS (\u20AA)", currencySymbol: "\u20AA" },
  QAT: { language: "Arabic, English", currency: "QAR (QR)", currencySymbol: "QR" },
  ROU: { language: "Romanian", currency: "RON (lei)", currencySymbol: "lei" },
  RUS: { language: "Russian", currency: "RUB (\u20BD)", currencySymbol: "\u20BD" },
  RWA: { language: "Kinyarwanda, English, French", currency: "RWF (FRw)", currencySymbol: "FRw" },
  SAU: { language: "Arabic", currency: "SAR (SR)", currencySymbol: "SR" },
  SDN: { language: "Arabic, English", currency: "SDG (SDG)", currencySymbol: "SDG" },
  SEN: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  SGP: { language: "English", currency: "SGD (S$)", currencySymbol: "S$" },
  SLB: { language: "English", currency: "SBD (SI$)", currencySymbol: "SI$" },
  SLE: { language: "English", currency: "SLE (Le)", currencySymbol: "Le" },
  SLV: { language: "Spanish", currency: "USD ($)", currencySymbol: "$" },
  SMR: { language: "Italian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  SOM: { language: "Somali, Arabic", currency: "SOS (Sh)", currencySymbol: "Sh" },
  SRB: { language: "Serbian", currency: "RSD (din)", currencySymbol: "din" },
  SSD: { language: "English", currency: "SSP (SSP)", currencySymbol: "SSP" },
  STP: { language: "Portuguese", currency: "STN (Db)", currencySymbol: "Db" },
  SUR: { language: "Dutch", currency: "SRD ($)", currencySymbol: "$" },
  SVK: { language: "Slovak", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  SVN: { language: "Slovenian", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  SWE: { language: "Swedish", currency: "SEK (kr)", currencySymbol: "kr" },
  SWZ: { language: "English, Swazi", currency: "SZL (E)", currencySymbol: "E" },
  SYC: { language: "English, French, Seychellois Creole", currency: "SCR (Rs)", currencySymbol: "Rs" },
  SYR: { language: "Arabic", currency: "SYP (LS)", currencySymbol: "LS" },
  TCD: { language: "French, Arabic", currency: "XAF (FCFA)", currencySymbol: "FCFA" },
  TGO: { language: "French", currency: "XOF (CFA)", currencySymbol: "CFA" },
  THA: { language: "Thai", currency: "THB (\u0E3F)", currencySymbol: "\u0E3F" },
  TJK: { language: "Tajik", currency: "TJS (SM)", currencySymbol: "SM" },
  TKM: { language: "Turkmen", currency: "TMT (m)", currencySymbol: "m" },
  TLS: { language: "Tetum, Portuguese", currency: "USD ($)", currencySymbol: "$" },
  TON: { language: "Tongan, English", currency: "TOP (T$)", currencySymbol: "T$" },
  TTO: { language: "English", currency: "TTD (TT$)", currencySymbol: "TT$" },
  TUN: { language: "Arabic, French", currency: "TND (DT)", currencySymbol: "DT" },
  TUR: { language: "Turkish", currency: "TRY (\u20BA)", currencySymbol: "\u20BA" },
  TUV: { language: "Tuvaluan, English", currency: "AUD (A$)", currencySymbol: "A$" },
  TWN: { language: "Mandarin", currency: "TWD (NT$)", currencySymbol: "NT$" },
  TZA: { language: "Swahili, English", currency: "TZS (TSh)", currencySymbol: "TSh" },
  UGA: { language: "English, Swahili", currency: "UGX (USh)", currencySymbol: "USh" },
  UKR: { language: "Ukrainian", currency: "UAH (\u20B4)", currencySymbol: "\u20B4" },
  URY: { language: "Spanish", currency: "UYU ($)", currencySymbol: "$" },
  USA: { language: "English", currency: "USD ($)", currencySymbol: "$" },
  UZB: { language: "Uzbek", currency: "UZS (so'm)", currencySymbol: "so'm" },
  VAT: { language: "Italian, Latin", currency: "EUR (\u20AC)", currencySymbol: "\u20AC" },
  VCT: { language: "English", currency: "XCD ($)", currencySymbol: "$" },
  VEN: { language: "Spanish", currency: "VES (Bs)", currencySymbol: "Bs" },
  VNM: { language: "Vietnamese", currency: "VND (\u20AB)", currencySymbol: "\u20AB" },
  VUT: { language: "Bislama, English, French", currency: "VUV (VT)", currencySymbol: "VT" },
  WSM: { language: "Samoan, English", currency: "WST (WS$)", currencySymbol: "WS$" },
  YEM: { language: "Arabic", currency: "YER (YR)", currencySymbol: "YR" },
  ZAF: { language: "English, Afrikaans, Zulu", currency: "ZAR (R)", currencySymbol: "R" },
  ZMB: { language: "English", currency: "ZMW (ZK)", currencySymbol: "ZK" },
  ZWE: { language: "English", currency: "ZWL ($)", currencySymbol: "$" },
};

export function getQuickFacts(isoCode: string): CountryQuickFacts | null {
  if (!isoCode) return null;
  return COUNTRY_QUICK_FACTS[isoCode.trim().toUpperCase()] ?? null;
}
